### ISSUE TITLE
Coverage no longer uploaded to codacy

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/hydropandas#298]
If we want our coverage status back we need to upload the coverage report to codacy using some github action, I believe.

e.g.

```yaml
      - name: Run codacy-coverage-reporter
        if: ${{ github.repository == 'ArtesiaWater/hydropandas && success() }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
```
